### PR TITLE
Fix codespace issue

### PR DESCRIPTION
**Pull request by Kostis-S-Z**
# What's changing

Currently the `.devcontainer.json` is ignored because its under the `.github` directory. It needs to be either in `root` or `.devcontainer/` according to the [docs](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#default-configuration-selection-during-codespace-creation).

This meant that the default configuration of codespaces for a machine with 16GB RAM was ignored, and instead was using the 8GB RAM machine which is not sufficient to properly run the demo app in codespaces. Thanks @ameckes1229 for the discovery!

Also the pre-installation step used in the `.devcontainer.json` was deprecated and now its updated to use the `.github/setup.sh` script.

# How to test it

Steps to test the changes:

1. Create default codespace (just by clicking `+`)
2. Click `Code` in the repo -> `...` in the active codespace -> `Change machine type` ->  Verify that the machine selected is the 16GB one
3. Run the demo in codespaces **without first installing anything**. The installation of the package should already been taken care of automatically when setting up the codespace.

# Additional notes for reviewers

~~Not sure how we can test this before merging to main :/~~

Edit: The only way to test this (to my understanding) is by using [pre-build codespaces](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-github-codespaces-prebuilds), but we need to discuss how or if we can set this up on org level. About testing codespaces configuration changes [here](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/testing-dev-container-changes)

# I already...

- [ ] Tested the changes in a working environment to ensure they work as expected
- [ ] Added some tests for any new functionality
- [x] Updated the documentation (both comments in code and under `/docs`)

### CODE REVIEW

**Comment by stefanfrench** [comment]
@Kostis-S-Z - i just tried to test this. I may be doing something wrong, but on this branch, I created default codespace and it did the 8GB version, not the 16GB version.

Also, i tried just running  `python -m streamlit run demo/app.py`   but got the following error: `/home/codespace/.python/current/bin/python: No module named streamlit`

**Comment by daavoo** [comment]
image

**Comment by daavoo** [comment]
> Edit: The only way to test this (to my understanding) is by using [pre-build codespaces](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-github-codespaces-prebuilds), but we need to discuss how or if we can set this up on org level. About testing codespaces configuration changes [here](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/testing-dev-container-changes)

I think is ok to merge and test from `main` to see if this works as expected. pre-build are a different purpose feature (still could be also interesting to look into it)

**Comment by daavoo** [comment]
It looks like these changes had no effect, I tested the default creation from main after merging this PR

**Pull request merged**
